name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup env vars
        run: |
          printf "${{secrets.BUILD_ENVIRONMENT_VARIABLES}}" > .env.production
      - name: Build the Docker image
        run: |
          sh manage.sh build
      - name: Push docker image to docker hub
        run: |
          echo "${{secrets.DOCKER_PASSWORD}}" | docker login --username ${{secrets.DOCKER_USER}} --password-stdin
          sh manage.sh push-img

  deploy:
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Reload ubicor frontend service on server
        run: |
          echo "${{secrets.AMAZON_SERVER_KEY}}" > server-key.pem
          chmod 600 server-key.pem
          sh manage.sh deploy
